### ISSUE TITLE
HomeWork_stack/ex_stack.py

### ISSUE THREAD

**Issue by TheML9I** [misha-sauchuk/python130218-HW1#12]
To avoid code duplication and 'global' usage try to refactor your code so that stack's functions will return stack state without changing within.

**Comment by misha-sauchuk** [comment]
I just assign my list to function call and I don't need 'global' now.
https://github.com/misha-sauchuk/python130218-HW1/blob/888e6ef15d73af81e4a505459e24d1c23fe4376d/HomeWork_stack/ex_stack.py#L48
